= `pre-receive` – enforce Angular commit message style guide (server-side)

`pre-receive` is a git hook script to enforce the Angular commit message style guide on the server-side.

= Installation on plain Git server
Just install `pre-receive` as server-side hook on your git server.

Be aware, that git only supports one `pre-receive` hook script. So you must implement a delegate script if one is already present.

== Installation on Gitlab
Gitlab support link:http://doc.gitlab.com/ce/hooks/custom_hooks.html[custom Git hooks]. The setup is rather easy. Simply copy the
script into `repositories/<group>/<project>.git/.git/custom_hooks` and mark it as executable. Make sure `pre-receive` matches the
file name.

== Usage

If a commit does not comply to the link:https://github.com/angular/angular.js/blob/v1.5.0/CONTRIBUTING.md#commit[Angular commit
style guide] it will fail and abort the commit with the following message.

**Additionally to the cited style guide it also checks for at least 7 characters after the colon (`:`)`.**

----
~ git push ssh://git@localhost:10022/ben/qa.git test/commit-enforcement
Zähle Objekte: 6, Fertig.
Delta compression using up to 4 threads.
Komprimiere Objekte: 100% (5/5), Fertig.
Schreibe Objekte: 100% (6/6), 1.14 KiB | 0 bytes/s, Fertig.
Total 6 (delta 2), reused 0 (delta 0)
remote: Invalid commit message format for a881e515de5d0024c6c1141a296aab794fe82e53: blurb
remote:
remote: ================================================================================
remote: ERROR: 1 commit message(s) do not following the commit styleguide.
remote:        Please check the following guide or use '// @formatter:off':
remote:        https://github.com/angular/angular.js/blob/v1.5.0/CONTRIBUTING.md#commit
remote: ================================================================================
remote:
remote: SYNTAX:
remote:     <type>(<scope>): <subject>
remote:
remote:     <descriptive body>
remote:
remote: TYPE:
remote:      feat: A new feature              fix: A bug fix
remote:      docs: Documentation changes     test: Adding tests
remote:     style: Changes that do not affect the meaning of the code
remote:      perf: A code change that improves performance
remote:  refactor: A code change that neither fixes a bug nor adds a feature
remote:     chore: Changes to the build process or auxiliary tools and libraries
remote:
remote: EXAMPLE:
remote:     perf(ngAnimate): avoid jqLite/jQuery for upward DOM traversal
remote:
remote:     The 'parentNode' property is well supported between all browsers. Since
remote:     no other functionality was required here, we can use the DOM API directly.
To ssh://git@localhost:10022/ben/qa.git
 ! [remote rejected] test/commit-enforcement -> test/commit-enforcement (pre-receive hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'ssh://git@localhost:10022/ben/qa.git'
----

== Supressing check

You can stop the enforcement of all older commits if you add `// @formatter:off` to the message of a commit.

This is especially useful on starting / introducing the commit message style guide in a project, because creating a new branch
will always contain _all_ parent commits and potentially legacy commits not complying to the style guide.

== Allowing default messages for merge and revert

For `git revert` and `git merge` operations, git applies and sometimes uses without confirmation
 default message, which do not comply with the Angular styleguide.

In case you do now want to impose unecessary obstacles you can configure `pre-receive` to accept
  these sort of messages by changing to configuration values inside the script.

.`$allowGitRevert`
If `1`, this allow default generated Git commit messages revert. Defaults to `0`.

> Revert "<original message>"

.`$allowGitMerge`
If `1`, this allow default generated Git commit messages for merge commits. Defaults to `0`.

> Merge branch '<sourcebranch>' into <target>